[package]
name = "apollo-crypto-python"
version = "0.1.0"
authors = ["Adam Budziak <adambudziak@protonmail.com>"]
edition = "2018"


[lib]
name = "apollo_crypto"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.2"
features = ["extension-module"]
